- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: us-east-1
      instance_type: t2.micro
      ami: ami-06b5810be11add0e2  # Ubuntu 16.04 LTS
      keypair: mykey
      security_group_names: Ansible-tower
      subnet_id: subnet-e1050085
  
  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group_names }}"  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         vpc_subnet_id: "{{ subnet_id }}"
         assign_public_ip: yes
      register: ec2
